#!/bin/bash

# Set the value of this variable to the prefix of your project.
PREFIX=IMR

# Define a variable named <PREFIX>_DIR in your bash_profile.
# i.e. CHARP_DIR=/path/to/charp-project

# These may be overriden by variables of the form <<PREFIX>>_<<VAR>>
# i.e. CHARP_DB_DATABASE overrides DB_DATABASE.
DB_DATABASE=imr
DB_HOST=localhost
DB_PORT=5432
DB_USER=imr

# This is usually correct:
DB_SUPERUSER=postgres

# pg for PostgreSQL, mysql for MySQL
DB_TYPE=pg

# Platform under which the DBMS is running. Valid values: win cygwin unix
DB_OS=unix

# Location of the ->SQL export generated by Power Architect
# (Uncomment and set accordingly if you are using Power Architect)
SQL_EXPORT="$HOME/imr.sql"

# You may want to set this to a locale suitable to your country.
# This is for Spanish/Mexico, UTF-8 (CHARP uses UTF-8 all around,
# it is not recommended to switch to a diferent encoding).
DB_LOCALE=es_MX.utf8
DB_COLLATE=es_MX.utf8

if [ $DB_TYPE = "pg" -a $DB_OS = "win" ]; then
	# Locales under Windows have a different nomeclature and Postgres
	# is system-dependent for locale specification. Set this accordingly 
	# if you are using Postgres for Windows.
	DB_LOCALE="«Spanish, Mexico»"
	DB_COLLATE="«Spanish, Mexico»"
fi

# Set this accordingly if you are using Cygwin and need to run
# the native executables instead of the ones from Cygwin.
# Otherwise, leave it commented.
#DB_BINDIR="/cygdrive/c/Program Files/PostgreSQL/9.3/bin/"

# *** No further editing needed after this line. ***

function prefix { local var=${PREFIX}_$1; echo -n ${!var}; }

CONF_DIR=$(prefix DIR)
[ -z "$CONF_DIR" ] && echo Variable ${PREFIX}DIR is not defined. >&2 && exit 1
[ ! -d "$CONF_DIR" ] && echo ${PREFIX}DIR value $CONF_DIR is not a directory. >&2 && exit 1

source "$CONF_DIR"/conf/scripts/config-script.sh
