#!/bin/bash

# Set the value of this variable to the prefix of your project.
PREFIX=IMR

# Location of the ->SQL export generated by Power Architect
# (Uncomment and set accordingly if you are using Power Architect)
SQL_EXPORT="$HOME/imr.sql"

# You may want to set this to a locale suitable to your country.
# This is for Spanish/Mexico, UTF-8 (CHARP uses UTF-8 all around,
# it is not recommended to switch to a diferent encoding).
DB_LOCALE=es_MX.utf8

# Locales under Windows have a different nomeclature and Postgres
# is system-dependent for locale specification. Uncomment and set 
# this accordingly if you are using Postgres for Windows.
#DB_LOCALE_WIN="Spanish, Mexico"

# Set this accordingly if you are using Cygwin and need to run
# the native executables instead of the ones from Cygwin.
# Otherwise, leave it commented.
#PGBINDIR="/cygdrive/c/Program Files/PostgreSQL/9.0/bin/"

# This is usually correct:
PGSUPERUSER=postgres

# *** No further editing needed after this line. ***
CONF_DIR=${PREFIX}DIR
source ${!CONF_DIR}/conf/config-script.sh
