
// This file has been generated by the GUI designer. Do not modify.
namespace IMRpatient
{
	public partial class WelcomeDlg
	{
		private global::Gtk.Fixed fixed1;
		private global::Gtk.Image image1;
		private global::Gtk.Table table1;
		private global::Gtk.Button buttonConf;
		private global::Gtk.Button buttonOk;
		private global::Gtk.Entry entryPasswd;
		private global::Gtk.Entry entryUser;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget IMRpatient.WelcomeDlg
			this.WidthRequest = 500;
			this.HeightRequest = 250;
			this.Name = "IMRpatient.WelcomeDlg";
			this.Title = "Welcome";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("IMRpatient.img.imr.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 500;
			this.DefaultHeight = 250;
			// Container child IMRpatient.WelcomeDlg.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.WidthRequest = 500;
			this.fixed1.HeightRequest = 250;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image1 = new global::Gtk.Image ();
			this.image1.WidthRequest = 500;
			this.image1.HeightRequest = 250;
			this.image1.Name = "image1";
			this.image1.Xalign = 0F;
			this.image1.Yalign = 0F;
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("IMRpatient.img.auth.png");
			this.fixed1.Add (this.image1);
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(2));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.buttonConf = new global::Gtk.Button ();
			this.buttonConf.CanFocus = true;
			this.buttonConf.Name = "buttonConf";
			this.buttonConf.UseUnderline = true;
			// Container child buttonConf.Gtk.Container+ContainerChild
			global::Gtk.Alignment w2 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w3 = new global::Gtk.HBox ();
			w3.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Menu);
			w3.Add (w4);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w6.LabelProp = global::Mono.Unix.Catalog.GetString (" _Configuration ");
			w6.UseUnderline = true;
			w3.Add (w6);
			w2.Add (w3);
			this.buttonConf.Add (w2);
			this.table1.Add (this.buttonConf);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonConf]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w12 = new global::Gtk.HBox ();
			w12.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w12.Add (w13);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w15 = new global::Gtk.Label ();
			w15.LabelProp = global::Mono.Unix.Catalog.GetString ("_OK");
			w15.UseUnderline = true;
			w12.Add (w15);
			w11.Add (w12);
			this.buttonOk.Add (w11);
			this.table1.Add (this.buttonOk);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonOk]));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryPasswd = new global::Gtk.Entry ();
			this.entryPasswd.CanFocus = true;
			this.entryPasswd.Name = "entryPasswd";
			this.entryPasswd.Text = global::Mono.Unix.Catalog.GetString ("Password");
			this.entryPasswd.IsEditable = true;
			this.entryPasswd.HasFrame = false;
			this.entryPasswd.InvisibleChar = '•';
			this.table1.Add (this.entryPasswd);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryPasswd]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entryUser = new global::Gtk.Entry ();
			this.entryUser.CanFocus = true;
			this.entryUser.Name = "entryUser";
			this.entryUser.Text = global::Mono.Unix.Catalog.GetString ("Username");
			this.entryUser.IsEditable = true;
			this.entryUser.HasFrame = false;
			this.entryUser.ActivatesDefault = true;
			this.entryUser.InvisibleChar = '•';
			this.table1.Add (this.entryUser);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.entryUser]));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			this.fixed1.Add (this.table1);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.table1]));
			w22.X = 10;
			w22.Y = 159;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Instituto Mexicano de Radiónica</b>");
			this.label1.UseMarkup = true;
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w23.X = 12;
			w23.Y = 229;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"white\"><b>Instituto Mexicano de Radiónica</b></span>");
			this.label2.UseMarkup = true;
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w24.X = 10;
			w24.Y = 228;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.entryPasswd.Activated += new global::System.EventHandler (this.OnEntryPasswdActivated);
			this.entryPasswd.Changed += new global::System.EventHandler (this.OnEntryPasswdChanged);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
			this.buttonConf.Clicked += new global::System.EventHandler (this.OnButtonConfClicked);
		}
	}
}
