-- Catalog COPYs. An example for locating the files is included.
-- BEGIN TRANSACTION;
-- 	SET CONSTRAINTS ALL DEFERRED;	
-- 
-- 	\echo 'my_catalog'
-- 	DELETE FROM my_catalog;
-- 	COPY my_catalog (col1, col2, col3) 
-- 	     FROM 'M4_DEFN(sqldir)/catalogs/my_catalog.csv' WITH (FORMAT csv, HEADER TRUE, DELIMITER '|', QUOTE '"');
-- COMMIT TRANSACTION;
